#!/bin/bash
sudo apt-get update
sudo apt-get install nodejs -y
sudo apt-get install npm -y
sudo apt-get install python3.5 -y
sudo apt-get install python3-pip -y
sudo apt-get install nodejs-legacy
sudo apt-get install phantomjs
pip3 install virtualenv
npm install
mkdir venv
virtualenv -p python3.5 venv
. ./venv/bin/activate
pip install -r pip.txt
sudo npm install forever -g
sudo npm install -g casperjs
